### ISSUE TITLE
NodeMCU or nano instead Uno

### ISSUE THREAD

**Issue by AmbiMod** [sergeich5/Ambilight-MacOS#1]
Hi my friend,

I recently purchase a Mac ( the M1 version ) and I want to put an Ambilight on it like I did on my previous windows laptop.

I used to manipulate ESP8266 or ESP32. Do you think you can do something to make it working with this NodeMCU ?

Or, if you can't, can I use an Arduino Nano instead the Uno ?

I hope you can do something, that will be great.

Thanks. 🙏

**Comment by sergeich5** [comment]
I suppose u can use Arduino Nano. Unfortunately, I don't have that Arduino to test myself, so I'm waiting for ur feedback!

**Comment by AmbiMod** [comment]
So my friend,

I received my Arduino Nano but I have two problem.

The first one is during the compilation of the device. A file is missing, Thread.h so I deleted some lines to finish the programmation but I guess I need this file after if I use your system.

![Capture d’écran 2021-05-23 à 13 29 24](https://user-images.githubusercontent.com/26428901/119258883-f0f0cc00-bbcb-11eb-9295-26ce51f64edc.jpg)

Like that you can see the name of the device detected on my Mac by Arduino IDE.

![Capture d’écran 2021-05-23 à 13 33 02](https://user-images.githubusercontent.com/26428901/119258908-05cd5f80-bbcc-11eb-872c-c9d1c5f36635.jpg)


The second thing is when I want to start the program. I have this message 

![Capture d’écran 2021-05-23 à 13 29 12](https://user-images.githubusercontent.com/26428901/119259138-10d4bf80-bbcd-11eb-9a4f-4773efb86883.jpg)

I think the name had to be changed to work with Arduino Nano. I hope you can do something for me.

Regards.

**Comment by AmbiMod** [comment]
Hi,

I made some modifications on my Mac :

I installed pyserial and requests so the errors are gone at launch are gone

When I launch your script, the system told me to give an access to Terminal for screen recording. I check the box but I have another error message as you can see :

![Capture d’écran 2021-05-25 à 19 52 34](https://user-images.githubusercontent.com/26428901/119545614-4e834500-bd93-11eb-9edf-18c23aac28b2.jpg)

Regards.

**Comment by sergeich5** [comment]
> A file is missing, Thread.h

Did you install Thread Library? See official site: https://www.arduino.cc/reference/en/libraries/thread/

> but I have another error message as you can see 

seems script has problems connecting with Arduino

**Comment by AmbiMod** [comment]
Stupid I'm, I forgot this library, sorry. 😣 

So i installed this missing library but I always have a compilation problem.

![Capture d’écran 2021-05-27 à 21 22 13](https://user-images.githubusercontent.com/26428901/119885447-24b45480-bf32-11eb-948c-00cd4a8cf7d2.jpg)

What do you think about this new error ? Note that I didn't change anything in your code.

**Comment by sergeich5** [comment]
> What do you think about this new error ? Note that I didn't change anything in your code.

seems there is not Thread library

**Comment by pparrilla** [comment]
I had the same problem, the thread library is https://github.com/ivanseidel/ArduinoThread. Install directly from Arduino IDE with Manage Library and include to the project
